package model;

public class Lansia {
    private int id;
    private String nama;
    private int usia;
    private int gulaDarah;
    private int tdDiastolik;
    private int tdSistolik;
    private String catatan;

    // Constructor for creating new Lansia without ID (ID is auto-generated by DB)
    public Lansia(String nama, int usia, int gulaDarah, int tdDiastolik, int tdSistolik, String catatan) {
        this.nama = nama;
        this.usia = usia;
        this.gulaDarah = gulaDarah;
        this.tdDiastolik = tdDiastolik;
        this.tdSistolik = tdSistolik;
        this.catatan = catatan;
    }

    // Constructor for retrieving from DB (includes ID)
    public Lansia(int id, String nama, int usia, int gulaDarah, int tdDiastolik, int tdSistolik, String catatan) {
        this.id = id;
        this.nama = nama;
        this.usia = usia;
        this.gulaDarah = gulaDarah;
        this.tdDiastolik = tdDiastolik;
        this.tdSistolik = tdSistolik;
        this.catatan = catatan;
    }

    // Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public int getUsia() {
        return usia;
    }

    public void setUsia(int usia) {
        this.usia = usia;
    }

    public int getGulaDarah() {
        return gulaDarah;
    }

    public void setGulaDarah(int gulaDarah) {
        this.gulaDarah = gulaDarah;
    }

    public int getTdDiastolik() {
        return tdDiastolik;
    }

    public void setTdDiastolik(int tdDiastolik) {
        this.tdDiastolik = tdDiastolik;
    }

    public int getTdSistolik() {
        return tdSistolik;
    }

    public void setTdSistolik(int tdSistolik) {
        this.tdSistolik = tdSistolik;
    }

    public String getCatatan() {
        return catatan;
    }

    public void setCatatan(String catatan) {
        this.catatan = catatan;
    }

    @Override
    public String toString() {
        return id + ". " + nama + " - " + usia + " tahun, Gula Darah: " + gulaDarah + ", TD: " + tdSistolik + "/" + tdDiastolik + ", Catatan: " + catatan;
    }
}